### ISSUE TITLE
TypeError: Cannot read property 'splice' of null

### ISSUE THREAD

**Issue by albabosh** [lafin/ru-yts#23]
# nodejs server/app.js --only-worker
start page: 1
/root/ru-yts/server/worker.js:122
    var tiles = tilesRe.exec(data).splice(1);
                                  ^

TypeError: Cannot read property 'splice' of null
    at getPageData (/root/ru-yts/server/worker.js:122:35)
    at /root/ru-yts/server/worker.js:153:20
    at Request._callback (/root/ru-yts/server/worker.js:22:16)
    at Request.self.callback (/root/ru-yts/node_modules/request/request.js:186:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/root/ru-yts/node_modules/request/request.js:1081:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/root/ru-yts/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by albabosh** [comment]
start page: 1                                                                                                                                            
No data                                                                                                                                                  
start page: 1                                                                                                                                            
No data                                                                                                                                                  
start page: 1                                                                                                                                            
No data                                                                                                                                                  
start page: 1                                                                                                                                            
No data                                                                                                                                                  
start page: 1                                                                                                                                            
No data                                                                                                                                                  
start page: 1                                                                                                                                            
No data                                                                                                                                                  
start page: 1                                                                                                                                            
No data                                                                                                                                                  
start page: 1
